name: "azlogin"
shortDesc: "Azure AD authentication"
longDesc: "Retrieves an authentication token from Azure AD"
command: "./azlogin.py"
flags:
  - name: "user"
    shorthand: "u"
    desc: "username"
    defValue: "default"
  - name: "tenant"
    shorthand: "t"
    desc: "Azure AD tenant id"
  - name: "appid"
    shorthand: "a"
    desc: "Kubernetes Azure AD Application id"
  - name: "clientid"
    shorthand: "c"
    desc: "Azure AD Application that has access to the Kubernetes application"
